import { ComponentSchema, IslandProps } from "../types";
import { safeLucideIcon } from "../lib/safe";
import { HelpCircle } from "lucide-react";
import React, { 
    createContext, 
    Fragment, 
    lazy, 
    Suspense, 
    useMemo,
    useContext,
    useState,
    useEffect
} from "preact/compat";

// --- IMPORT INTERNAL COMPONENTS ---
import { Section } from "../ui/brainwave/section";
import { Container } from "../ui/brainwave/container";
import { Typography } from "../ui/brainwave/typography";
import { ANIM, MotionDiv, MotionH1, MotionH2, MotionH3, MotionP, MotionSpan } from "../lib/motion";
import { ErrorBoundary } from "../lib/error-boundry";
import ScenePlaceholder from "../ui/spline/scene-paceholder";

// --- IMPORT MANIFEST (AUTO-GENERATED BY SCANNER) ---
import { COMPONENT_LOADERS } from "assets/ts/client-manifest"; 

// --- 1. TYPE DEFINITIONS ---

type ScopeType = Record<string, any>;

type EffectDefinition = {
    deps?: string[];
    code: string;
};

// --- 2. SCOPE CONTEXT ---
const ScopeContext = createContext<ScopeType>({});


// --- 3. UNIVERSAL HELPERS ---

const injectTemplateData = (obj: any, scope: ScopeType): any => {
    if (typeof obj === 'string') {
        // 1. PRIORITAS UTAMA: Pure Variable (Agar tipe data Object/Array terjaga)
        const pureMatch = obj.match(/^\$\{([^}]+)\}$/);
        
        if (pureMatch) {
            const exp = pureMatch[1];
            try {
                const keys = Object.keys(scope);
                const values = Object.values(scope);
                const result = new Function(...keys, `return ${exp}`)(...values);
                return result !== undefined ? result : obj;
            } catch (e) {
                // Ignore error, return original
            }
        }

        // 2. PRIORITAS KEDUA: String Interpolation
        return obj.replace(/\$\{([^}]+)\}/g, (match, exp) => {
            try {
                const keys = Object.keys(scope);
                const values = Object.values(scope);
                const result = new Function(...keys, `return ${exp}`)(...values);
                return result !== undefined ? String(result) : ""; 
            } catch (e) {
                return match; 
            }
        });
    }

    if (Array.isArray(obj)) {
        return obj.map(child => injectTemplateData(child, scope));
    }

    if (obj && typeof obj === 'object') {
        const result: any = {};
        for (const key in obj) {
            result[key] = injectTemplateData(obj[key], scope);
        }
        return result;
    }

    return obj;
};

const hydrateProps = (props: Record<string, any> = {}, scope: ScopeType = {}): Record<string, any> => {
    const hydrated: Record<string, any> = {};

    Object.keys(props).forEach((key) => {
        const value = props[key];
        
        if (typeof value === 'string') {
            const trimmed = value.trim();

            // 1. Deteksi Fungsi
            if (trimmed.startsWith('() =>') || trimmed.startsWith('(e) =>') || trimmed.startsWith('function')) {
                try {
                    const keys = Object.keys(scope);
                    const values = Object.values(scope);
                    const factory = new Function(...keys, `return ${trimmed}`);
                    const fn = factory(...values);
                    if (typeof fn === 'function') {
                        hydrated[key] = fn;
                        return;
                    }
                } catch (err) {}
            }

            // 2. Deteksi Objek/Array (JSON-like string)
            const isObject = (trimmed.startsWith('{') && trimmed.endsWith('}'));
            const isArray = (trimmed.startsWith('[') && trimmed.endsWith(']'));
            
            if (isObject || isArray) {
                try {
                    let jsExpression = trimmed;
                    if (trimmed.startsWith('{{') && trimmed.endsWith('}}')) {
                        jsExpression = trimmed.slice(1, -1); 
                    }
                    const keys = Object.keys(scope);
                    const values = Object.values(scope);
                    const result = new Function(...keys, `return ${jsExpression}`)(...values);
                    hydrated[key] = result;
                    return; 
                } catch (e) {
                    console.warn(`[Hydrator] Failed to parse object: ${key}`, e);
                }
            }
        }
        
        hydrated[key] = value;
    });
    return hydrated;
};

const resolveDependencies = (deps: string[] = [], scope: ScopeType): any[] => {
    if (!deps) return [];
    return deps.map(depKey => {
        try {
            const keys = Object.keys(scope);
            const values = Object.values(scope);
            return new Function(...keys, `return ${depKey}`)(...values);
        } catch (e) {
            return undefined;
        }
    });
};


// --- 4. LOGIC COMPONENTS ---

const Mapper = ({ data, template }: { data: any[], template: ComponentSchema }) => {
    const parentScope = useContext(ScopeContext);
    
    if (!data || !Array.isArray(data) || !template) return null;

    return (
        <Fragment>
            {data.map((item, index) => {
                const itemScope = {
                    ...parentScope,
                    item: item, 
                    index: index
                };
                return (
                    <ScopeContext.Provider key={index} value={itemScope}>
                        <Renderer schema={template} />
                    </ScopeContext.Provider>
                );
            })}
        </Fragment>
    );
};

const StateWrapper = ({ init, effects, schemaChildren }: { init: any, effects: EffectDefinition, schemaChildren: ComponentSchema[] }) => {
    const [state, setState] = useState(init || {});

    const setters = useMemo(() => {
        const helpers: Record<string, Function> = {};
        Object.keys(state).forEach(key => {
            helpers[key] = (val: any) => {
                setState((prev: any) => {
                    const newValue = typeof val === 'function' ? val(prev[key]) : val;
                    return { ...prev, [key]: newValue };
                });
            };
        });
        return helpers;
    }, [state]);

    const parentScope = useContext(ScopeContext);
    const currentScope = { ...parentScope, $state: state, $set: setters };

    if (effects && Array.isArray(effects)) {
        effects.forEach((effect, idx) => {
            const resolvedDeps = resolveDependencies(effect.deps, currentScope);
            useEffect(() => {
                try {
                    const fnStr = effect.code;
                    if (!fnStr) return;
                    const keys = Object.keys(currentScope);
                    const values = Object.values(currentScope);
                    const factory = new Function(...keys, `return ${fnStr}`);
                    const executableEffect = factory(...values);
                    if (typeof executableEffect === 'function') return executableEffect();
                } catch (err) {
                    console.error(`[State] Error effect #${idx}:`, err);
                }
                // eslint-disable-next-line react-hooks/exhaustive-deps
            }, resolvedDeps);
        });
    }

    return (
        <ScopeContext.Provider value={currentScope}>
            {schemaChildren && schemaChildren.map((child, idx) => (
                <Renderer key={idx} schema={child} />
            ))}
        </ScopeContext.Provider>
    );
};


// --- 5. COMPONENT RESOLVER (HYBRID ENGINE) ---

const INTERNAL_MAP: Record<string, React.ElementType> = {
    Section: Section,
    Container: Container,
    Map: Mapper,
    State: StateWrapper,
    ScenePlaceholder: ScenePlaceholder,
    MotionDiv: MotionDiv,
    MotionH1: MotionH1,
    MotionH2: MotionH2,
    MotionH3: MotionH3,
    MotionP: MotionP,
    MotionSpan: MotionSpan,
    Typography: Typography,
    ErrorBoundary: ErrorBoundary,
    Suspense: Suspense,
    Fragment: Fragment,
    Div: "div",
    Span: "span",
    Img: "img",
    Ul: "ul",
    Li: "li",
    P: "p",
    A: "a",
    Label: "label",
    Button: "button",
};

const resolveDynamicComponent = (componentName: string) => {
    // 1. STATIC: Cek Internal Map
    if (INTERNAL_MAP[componentName]) {
        return { mode: 'static', component: INTERNAL_MAP[componentName] };
    }

    // 2. ICON
    if (componentName === 'icon') {
        return { mode: 'icon' };
    }

    // 3. 🔥 MANIFEST LOOKUP (Prioritas Utama)
    // Cek apakah scanner sudah mendaftarkan komponen ini (termasuk shadcn/dialog-content)
    if (COMPONENT_LOADERS[componentName]) {
        return { mode: 'lazy', component: lazy(COMPONENT_LOADERS[componentName]) };
    }

    // 4. 🔥 DYNAMIC FALLBACK (The "Magic" Import)
    // Jika tidak ada di manifest, coba tebak lokasi filenya secara otomatis.
    const [pathPart, exportName] = componentName.split('.');
    const pathSegments = pathPart.split('/');
    
    if (pathSegments.length >= 2) {
        const folder = pathSegments[0];
        const file = pathSegments[1];

        const LazyComponent = lazy(async () => {
            try {
                let module: any;
                // Import dinamis (Mapping folder manual untuk esbuild)
                if (folder === 'components') {
                    module = await import(`../components/${file}.tsx`);
                } else if (folder === 'shadcn') {
                    module = await import(`../ui/shadcn/${file}.tsx`);
                } else if (folder === 'lightswind') {
                    module = await import(`../ui/lightswind/${file}.tsx`);
                } else if (folder === 'brainwave') {
                    module = await import(`../ui/brainwave/${file}.tsx`);
                } else if ( folder === 'spline') {
                    module = await import(`../ui/spline/${file}.tsx`);
                } else {
                    throw new Error(`Unknown UI folder: ${folder}`);
                }

                // Resolusi Export
                if (exportName) return { default: module[exportName] };
                if (module.default) return { default: module.default };
                
                // Fallback PascalCase
                const pascalName = file.charAt(0).toUpperCase() + file.slice(1);
                if (module[pascalName]) return { default: module[pascalName] };

                throw new Error(`Export not found`);
            } catch (err) {
                console.warn(`[UI-Engine] Dynamic load failed for ${componentName}. Is it in manifest?`);
                return { default: () => <div className="text-red-500 text-xs p-1 border border-red-500">Missing: {componentName}</div> };
            }
        });

        return { mode: 'lazy', component: LazyComponent };
    }

    return { mode: 'missing', name: componentName };
};


// --- 6. MAIN RENDERER ---

const Renderer = ({ schema }: { schema: ComponentSchema }) => {
    if (!schema || typeof schema !== 'object' || !schema.component) return null;

    const scope = useContext(ScopeContext);

    // Conditional
    if (schema.if !== undefined) {
        let shouldRender = schema.if;
        if (typeof schema.if === 'string' && schema.if.includes('${')) {
            const evaluated = injectTemplateData(schema.if, scope);
            shouldRender = evaluated === 'true' || (evaluated !== 'false' && evaluated !== '' && evaluated !== '0');
        }
        if (!shouldRender) return null;
    }

    // Inject Data
    const injectedSchema = useMemo(() => injectTemplateData(schema, scope), [schema, scope]);
    
    // Resolve
    const resolved = useMemo(() => resolveDynamicComponent(injectedSchema.component), [injectedSchema.component]);

    if (!resolved) return <div className="text-red-500">Render Error</div>;
    if (resolved.mode === 'missing') return <div className="text-orange-500">Missing: {injectedSchema.component}</div>;

    // Hydrate Props
    const rawProps = injectedSchema.props || {};
    const hydratedProps = useMemo(() => hydrateProps(rawProps, scope), [rawProps, scope]);

    // Fallback Handling
    if (rawProps.fallback && typeof rawProps.fallback === 'object') {
        const fallbackSchema = rawProps.fallback as ComponentSchema;
        if (fallbackSchema.component) {
            hydratedProps.fallback = <Renderer schema={fallbackSchema} />;
        }
    }

    const Component = resolved.component;

    // --- CHILDREN HANDLING ---
    let childrenToRender: any = injectedSchema.text || null;
    
    if (injectedSchema.children && injectedSchema.children.length > 0) {
        childrenToRender = injectedSchema.children.map((child: any, idx: number) => (
            <Renderer key={idx} schema={child} />
        ));
    }

    const extraProps = {
        schemaChildren: injectedSchema.children 
    };

    if (resolved.mode === 'icon') {
        const Icon = safeLucideIcon(hydratedProps.name as string) ?? HelpCircle;
        return <Icon {...hydratedProps} />;
    }

    if (resolved.mode === 'lazy') {
        // Handle explicit fallback from YAML prop if component is lazy
        const lazyFallback = hydratedProps.fallback || null;
        
        return (
            <Suspense fallback={lazyFallback}> 
                <Component {...hydratedProps} {...extraProps}>{childrenToRender}</Component>
            </Suspense>
        );
    }

    return <Component {...hydratedProps} {...extraProps}>{childrenToRender}</Component>;
};


// --- 7. ENTRY POINT ---
export const config = { 
    name: "ui-engine-client",
    moduleSource: ['islands', 'modules', 'core', 'ui-engine-client'],
    mode: 'interactive',
    outputDir: ['layouts', 'partials', 'core'], 
};

export default function UIEngineClient({ Data = {} }: IslandProps) {
    const tree = (Data as any).tree || [];
    const globalScope = {
        ANIM: ANIM,
        Math: Math,
        Date: Date,
    }

    return (
        <div className="ui-engine-client-root w-full">
            <ScopeContext.Provider value={globalScope}>
                {tree.map((node: any, idx: number) => (
                    <Renderer key={idx} schema={node} />
                ))}
            </ScopeContext.Provider>
        </div>
    );
}