# [style]
#     theme_variant = "brainwave"

# [header]
#     variant = "brainwave"

#     [header.logo] 
#         variant = "brainwave"
#         title="BRAINWAVE"
#         href = "/"

#         # Props Hootodus Logo
#         hotodus-class-name = ""
#         img-url = "images/exodus.svg"
#         img-alt = "braibnwave Logo"

#         # Props Brainwave Logo
#         brainwave-class-name = ""
#         scene-class-name = ""
#         # scene-url = "https://prod.spline.design/nGs82-D61fKK2zsY/scene.splinecode"
#         video-src = "videos/eye-anime-girl.mp4"
#         beam-size = 50
#         video-font-size = "1.875rem"
#         video-font-weight = 800 


