// ⚠️ AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by islands/core/scanner.ts

import { FunctionalComponent } from "preact";
import { IslandProps } from "@/modules/types";

type IslandModul = {
    default: FunctionalComponent<IslandProps>;
}

export const COMPONENT_LOADERS: Record<string, () => Promise<IslandModul>> = {
    "content-block": () => import("@/modules/components/content-block"),
    "cta": () => import("@/modules/components/cta"),
    "features": () => import("@/modules/components/features"),
    "form": () => import("@/modules/components/form"),
    "brainwave": () => import("@/modules/components/header/brainwave"),
    "hotodus": () => import("@/modules/components/header/hotodus"),
    "hero-modern": () => import("@/modules/components/hero-modern"),
    "hero": () => import("@/modules/components/hero"),
    "news": () => import("@/modules/components/news"),
    "stats": () => import("@/modules/components/stats"),
    "ui-engine": () => import("@/modules/core/ui-engine"),
};
